/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingCatalogRouteImport } from './routes/training-catalog'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MySessionsRouteImport } from './routes/my-sessions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const TrainingCatalogRoute = TrainingCatalogRouteImport.update({
  id: '/training-catalog',
  path: '/training-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsRoute = MySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-event': typeof CreateEventRoute
  '/employees': typeof EmployeesRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/training-catalog': typeof TrainingCatalogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-event': typeof CreateEventRoute
  '/employees': typeof EmployeesRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/training-catalog': typeof TrainingCatalogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-event': typeof CreateEventRoute
  '/employees': typeof EmployeesRoute
  '/events': typeof EventsRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/training-catalog': typeof TrainingCatalogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/create-event'
    | '/employees'
    | '/events'
    | '/health'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/teams'
    | '/training-catalog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/create-event'
    | '/employees'
    | '/events'
    | '/health'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/teams'
    | '/training-catalog'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/create-event'
    | '/employees'
    | '/events'
    | '/health'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/teams'
    | '/training-catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CreateEventRoute: typeof CreateEventRoute
  EmployeesRoute: typeof EmployeesRoute
  EventsRoute: typeof EventsRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  MySessionsRoute: typeof MySessionsRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRoute
  TrainingCatalogRoute: typeof TrainingCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-catalog': {
      id: '/training-catalog'
      path: '/training-catalog'
      fullPath: '/training-catalog'
      preLoaderRoute: typeof TrainingCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions': {
      id: '/my-sessions'
      path: '/my-sessions'
      fullPath: '/my-sessions'
      preLoaderRoute: typeof MySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CreateEventRoute: CreateEventRoute,
  EmployeesRoute: EmployeesRoute,
  EventsRoute: EventsRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  MySessionsRoute: MySessionsRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRoute,
  TrainingCatalogRoute: TrainingCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
